name: Quality Assurance

on: 
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  test:
    name: Ava Testing

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]
        pnpm: [8.x]
        packager: [pnpm]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: ${{ matrix.packager }}
      - name: Install Dependencies
        run: pnpm i
      - name: Run Tests
        run: pnpm test
      - name: Upload Coverage
        if: success()
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          coverageLocations: ${{ github.workspace }}/coverage/lcov.info:lcov
  lint:
    name: Linting

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.x]
        pnpm: [8.x]
        packager: [pnpm]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: ${{ matrix.packager }}
      - name: Install Dependencies
        run: pnpm i
      - name: Validate Typescript
        uses: fersilva16/ts-report-action@1.2.1
        with:
          project: tsconfig.eslint.json
      - name: Lint Code
        run: npm run lint